### ISSUE TITLE
nyu dataset processing

### ISSUE THREAD

**Issue by wwlonno** [amueller/datasets#1]
Hello, amueller.
In the nyu.py, there are some image files name in line 31, 35, 42, 54 and 74.  How to covert the labeled dataset nyu_depth_v2_labeled.mat to these files and store like this? Can you offer a converting scripts? Thank you.

**Comment by amueller** [comment]
Sorry, It's been a couple of years since I worked on this, and I don't remember how I loaded the data. I think this file is actually to load the output from some pixel-wise random forest predictions that were created in my lab in Bonn.

**Comment by wwlonno** [comment]
I am just running up your code on semantic segmentation. Anyway, thank you for your reply.
